config/routes.rb
Rails.application.routes.draw do

  resources :books
  root 'home#top'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
  	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  	  redirect_to @book
  	  flash[:notice] = "Book was successfully updated."
  	else
  	  render "edit"
  	end
  end

  def create
  	@book = Book.new(book_params)
  	@books = Book.all
  	if @book.save
  	  redirect_to @book
  	  flash[:notice] = "Book was successfully created."
    else
      render "index"
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<h1>Editing book</h1>
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<%= f.submit 'Update Book' %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>


<table>
<th>Title</th>
<th>Body</th>
<tr>
<% @books.each do|book|%>
<td><%= book.title%></td>
<td><%= book.body%></td>
<td><%= link_to "Show" , book_path(book)%></td>
<td><%= link_to "Edit" , edit_book_path(book) %></td>
<td><%= link_to "Destroy" , book_path(book) ,method: :delete %></td>
</tr>
</tbody>
<% end %>
</table>

<h1>New book</h1>
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@book) do |f| %>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<%if flash[:notice] %>
	<%= flash[:notice]%>
<% end %>
<p><strong>Title:</strong> <%= @book.title%></p>


<p><strong>Body:</strong> <%= @book.body%></p>

<%= link_to "Edit" , edit_book_path(@book)%>  | <%= link_to "Back" , books_path%>

app/views/home/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%=link_to"start",books_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>